### ISSUE TITLE
erro

### ISSUE THREAD

**Issue by wstroks** [godot-extended-libraries/godot-tensorflow-demo#1]
I'm having this error when I compile 

scons -j8 platform=x11

 71%] scons: *** [thirdparty/tensorflow/tensorflow/lite/nnapi_delegate.x11.tools.64.o] Source `thirdparty/tensorflow/tensorflow/lite/nnapi_delegate.cc' not found, needed by target `thirdparty/tensorflow/tensorflow/lite/nnapi_delegate.x11.tools.64.o'.

I tried everything but I can not solve!!!

**Comment by fire** [comment]
Hi, did you solve the problem?
